# Site settings
baseurl: "" 

# Color settings (Hex value without #)
color_alpha: feeaeb
color_beta: 05009e

# Google Analytics
google_analytics: UA-141012738-1

# Instagram API
instagram_key: 
instagram_caption: true

# SEO settings
title: Cocó en Barcelona
description: 
url: ""
email: caro@cocoenbarcelona.com
twitter_username: 
default_img: 

# Profile settings
social:
  instagram: https://www.instagram.com/carokakefuku/

# Build settings
exclude: ["node_modules", "gulpfile.js", "assets/js/app.js", "README.md", "Gemfile", "Gemfile.lock"]
markdown: kramdown
permalink: /:year/:month/:day/:title/

# Sass
sass:
  style: compressed

# Gems
gems: [jekyll-sitemap, octopress-autoprefixer]

theme: jekyll-theme-cayman